ERROR_MESSAGE_BACKEND = {'error' : "Something went wrong, please try reasking the same question or contact our support team if nothing works."}


BENCHMARKS = {
    "Nifty 50": "^NSEI" ,
    "Sensex" : "^BSESN",
    "Nifty Bank": "^NSEBANK",
    "Nifty IT" : "^CNXIT", 
    "Nifty FMCG" : "^CNXFMCG", 
    "Nifty Pharma" : "^CNXPHARMA",
    "Nifty Auto" : "^CNXAUTO",
    "Nifty Energy" : "^CNXENERGY",
    "Nifty Metal" : "^CNXMETAL"
}


# Nifty 50 Index Constituents
NIFTY_50_TICKERS = [
    "RELIANCE.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS", "TCS.NS", "HINDUNILVR.NS", "KOTAKBANK.NS",
    "LT.NS", "BAJFINANCE.NS", "ITC.NS", "AXISBANK.NS", "SBIN.NS", "MARUTI.NS", "ASIANPAINT.NS",
    "HCLTECH.NS", "WIPRO.NS", "TITAN.NS", "ULTRACEMCO.NS", "BHARTIARTL.NS", "SUNPHARMA.NS",
    "M&M.NS", "POWERGRID.NS", "NTPC.NS", "HDFCLIFE.NS", "ADANIGREEN.NS", "ADANIPORTS.NS",
    "DIVISLAB.NS", "TATAMOTORS.NS", "TATASTEEL.NS", "HINDALCO.NS", "SHREECEM.NS", "JSWSTEEL.NS",
    "TECHM.NS", "GRASIM.NS", "COALINDIA.NS", "BAJAJFINSV.NS", "DRREDDY.NS", "CIPLA.NS",
    "EICHERMOT.NS", "UPL.NS", "INDUSINDBK.NS", "BRITANNIA.NS", "HEROMOTOCO.NS", "ADANIPOWER.NS",
    "TATACONSUM.NS", "M&MFIN.NS", "TATAPOWER.NS", "BAJAJ-AUTO.NS", "SBILIFE.NS", "ICICIGI.NS"
]

# Nifty Bank Index Constituents
NIFTY_BANK_TICKERS = [
    "HDFCBANK.NS", "ICICIBANK.NS", "KOTAKBANK.NS", "AXISBANK.NS", "SBIN.NS", "BANKBARODA.NS",
    "PNB.NS", "IDFCFIRSTB.NS", "YESBANK.NS", "INDUSINDBK.NS", "BANDHANBNK.NS", "RBLBANK.NS"
]

# Nifty IT Index Constituents
NIFTY_IT_TICKERS = [
    "INFY.NS", "TCS.NS", "HCLTECH.NS", "WIPRO.NS", "TECHM.NS", "LTI.NS", "MPHASIS.NS",
    "COFORGE.NS", "MINDTREE.NS", "HAPPSTMNDS.NS", "ZENSARTECH.NS", "NIITTECH.NS"
]

# Nifty FMCG Index Constituents
NIFTY_FMCG_TICKERS = [
    "HINDUNILVR.NS", "ITC.NS", "TITAN.NS", "BRITANNIA.NS", "DABUR.NS", "MARICO.NS", "COLPAL.NS",
    "NESTLEIND.NS", "MCDOWELL-N.NS", "GODREJCP.NS", "HINDZINC.NS", "JUBLFOOD.NS", "PIDILITIND.NS"
]

# Nifty Pharma Index Constituents
NIFTY_PHARMA_TICKERS = [
    "SUNPHARMA.NS", "CIPLA.NS", "DRREDDY.NS", "LUPIN.NS", "AARTIDRUGS.NS", "ALKEM.NS", "TORNTPHARM.NS",
    "CADILAHC.NS", "DIVISLAB.NS", "IPCALAB.NS", "GLENMARK.NS", "BIOCON.NS"
]

# Nifty Auto Index Constituents
NIFTY_AUTO_TICKERS = [
    "MARUTI.NS", "EICHERMOT.NS", "BAJAJ-AUTO.NS", "M&M.NS", "TATAMOTORS.NS", "ASHOKLEY.NS",
    "EXIDEIND.NS", "BHARATFORG.NS", "TVSMOTOR.NS", "BOSCHLTD.NS", "SMLISUZU.NS", "AMARAJABAT.NS"
]

# Nifty Metal Index Constituents
NIFTY_METAL_TICKERS = [
    "TATASTEEL.NS", "JSWSTEEL.NS", "HINDALCO.NS", "COALINDIA.NS", "SAIL.NS", "NMDC.NS", "JINDALSTEL.NS",
    "VEDL.NS", "HINDZINC.NS", "INDIANB.NS", "TATAMETALI.NS", "HINDCOPPER.NS"
]

# Nifty Realty Index Constituents
NIFTY_REALTY_TICKERS = [
    "DLF.NS", "OBEROIRLTY.NS", "MAHINDCIE.NS", "BRIGADE.NS", "INDIACEM.NS", "SOBHA.NS", "PHOENIXLTD.NS",
    "PRESTIGE.NS", "SUNTECK.NS", "NCC.NS", "KOLTEPATIL.NS", "LUXIND.NS"
]

# Nifty Energy Index Constituents
NIFTY_ENERGY_TICKERS = [
    "RELIANCE.NS", "NTPC.NS", "ONGC.NS", "POWERGRID.NS", "GAIL.NS", "IOC.NS", "BPCL.NS", "EDELWEISS.NS",
    "ADANIGREEN.NS", "ADANIPORTS.NS", "ADANIPOWER.NS", "NTPC.NS"
]

# Nifty Consumption Index Constituents
NIFTY_CONSUMPTION_TICKERS = [
    "HINDUNILVR.NS", "ITC.NS", "TITAN.NS", "MARICO.NS", "DABUR.NS", "COLPAL.NS", "NESTLEIND.NS",
    "MCDOWELL-N.NS", "GODREJCP.NS", "HINDZINC.NS", "JUBLFOOD.NS", "PIDILITIND.NS"
]



BENCHMARKS_TO_STOCKS = {
    "Nifty 50": NIFTY_50_TICKERS,
    "Nifty Bank": NIFTY_BANK_TICKERS,
    "Nifty IT": NIFTY_IT_TICKERS,
    "Nifty FMCG": NIFTY_FMCG_TICKERS,
    "Nifty Pharma": NIFTY_PHARMA_TICKERS,
    "Nifty Auto": NIFTY_AUTO_TICKERS,
    "Nifty Metal": NIFTY_METAL_TICKERS,
    "Nifty Realty": NIFTY_REALTY_TICKERS,
    "Nifty Energy": NIFTY_ENERGY_TICKERS,
    "Nifty Consumption": NIFTY_CONSUMPTION_TICKERS
}